# Generated by Django 3.2.4 on 2021-07-09 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.TextField()),
                ('created_dt_tm', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_dt_tm', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
